#!/usr/bin/env python3
"""Generate five client rule sets from the reviewed domain manifest (stdlib only)."""

import argparse
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DOMAIN_RE = re.compile(r"(?=.{1,253}$)(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?$")


def load_services():
    data = json.loads((ROOT / "sources/foreign-ai.json").read_text(encoding="utf-8"))
    services = data["services"]
    seen = set()
    suffixes = {domain for service in services for domain in service["suffixes"]}
    for service in services:
        if not service["sources"]:
            raise ValueError(f"Missing sources: {service['id']}")
        for field in ("domains", "suffixes"):
            for domain in service[field]:
                if not DOMAIN_RE.fullmatch(domain):
                    raise ValueError(f"Invalid domain: {domain}")
                key = (field, domain)
                if key in seen:
                    raise ValueError(f"Duplicate rule: {key}")
                seen.add(key)
                parents = [s for s in suffixes if domain.endswith("." + s) or (field == "domains" and domain == s)]
                if parents:
                    raise ValueError(f"Redundant rule: {domain}, already covered by {parents}")
            service[field].sort()
    return data


def render(data):
    services = data["services"]
    count = sum(len(s["domains"]) + len(s["suffixes"]) for s in services)
    header = (
        "# Foreign AI - common overseas AI services\n"
        f"# Updated: {data['updated']}\n"
        f"# Services: {len(services)} | Rules: {count}\n"
        "# Generated from sources/foreign-ai.json; do not edit this file alone.\n"
        "# Sources and scope: README.md | Third-party license: THIRD_PARTY_NOTICES.md\n"
        "# Assign a proxy policy in the calling configuration.\n"
    )
    text_lines = []
    yaml_lines = ["payload:"]
    for service in services:
        text_lines += ["", "# " + service["name"]]
        yaml_lines += ["", "  # " + service["name"]]
        for kind, field in (("DOMAIN", "domains"), ("DOMAIN-SUFFIX", "suffixes")):
            for domain in service[field]:
                line = f"{kind},{domain}"
                text_lines.append(line)
                yaml_lines.append("  - " + line)
    egern_lines = []
    for kind, field in (("domain_set", "domains"), ("domain_suffix_set", "suffixes")):
        egern_lines += [kind + ":"]
        for service in services:
            if service[field]:
                egern_lines.append("  # " + service["name"])
                egern_lines.extend("  - " + domain for domain in service[field])
        egern_lines.append("")
    payload = header + "\n".join(yaml_lines) + "\n"
    text_rules = header + "\n".join(text_lines) + "\n"
    return {
        "rule/Clash/AI/AI.yaml": payload,
        "rule/Stash/AI/AI.yaml": payload,
        "rule/Loon/AI/AI.list": text_rules,
        "rule/Shadowrocket/AI/AI.list": text_rules,
        "rule/Egern/AI/AI.yaml": header + "\n".join(egern_lines),
    }


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Check committed outputs without writing")
    args = parser.parse_args()
    data = load_services()
    outputs = render(data)
    for relative, content in outputs.items():
        target = ROOT / relative
        encoded = content.encode("utf-8")
        if args.check:
            if not target.is_file() or target.read_bytes() != encoded:
                raise SystemExit(f"Outdated or missing: {relative}")
        else:
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_bytes(encoded)
    count = sum(len(s["domains"]) + len(s["suffixes"]) for s in data["services"])
    print(f"{'CHECK' if args.check else 'BUILD'} OK: {len(outputs)} files, {len(data['services'])} services, {count} rules per client")


if __name__ == "__main__":
    main()
